### ISSUE TITLE
Better document optional dependencies and backends

### ISSUE THREAD

**Issue by sebastinas** [JonnyJD/musicbrainz-isrcsubmit#103]
I think the all the stuff said in #763885 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763885#10) should be documented in isrcsubmit itself. The purpose of the cdrdao backend and keyring are not Debian specific.

**Comment by JonnyJD** [comment]
Hm, I wanted to create a separate PR, but I messed up and pushed to master instead..

This should be fixed with 635f29bbfd5aa2117b52e347d35998e61e2906c3.

Please comment and/or reopen if this needs more changes though.

**Comment by JonnyJD** [comment]
This was previously documented here: http://jonnyjd.github.io/musicbrainz-isrcsubmit/backends

Since we do have manpages we should also document it there (as is done with the mentioned commit).
We probably should also have a note in the README. Not sure if I should put a link to the web docs or duplicate the section from the man page.
