### ISSUE TITLE
isrcsubmit{,-git} PKGBUILDs do not build (DBusException)

### ISSUE THREAD

**Issue by Freso** [JonnyJD/musicbrainz-isrcsubmit#108]
See `makepkg` output at https://gist.github.com/Freso/d8f7441be9ff43ea2af8 on an otherwise updated x86_64 Arch Linux system.

**Comment by JonnyJD** [comment]
This seems to be an "upstream problem":
```
import keyring
...
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

Trying `import keyring` with the user currently using X/dbus works fine.
Changing to another user (like to build packages) with `su abs` breaks this because `DBUS_SESSION_BUS_ADDRESS` is set, but the corresponding socket is not accessible to the user `abs` so `import keyring` fails with the above error message.

So this is kind of similar (but not the same) as #90.

The current possible workarounds:

* `su - <abs user>`
* `env - makepkg`
* use `env -` in the `PKGBUILD`
* `unset DBUS_SESSION_BUS_ADDRESS` (with an additional `unset DISPLAY` otherwise build() takes longer)

The real solution is of course to report this upstream ([python-keyring](https://github.com/jaraco/keyring
) and that possibly leads to python-secretstorage then).

**Comment by JonnyJD** [comment]
Oh, my error message is different:
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Failed to connect to socket /run/user/1000/bus: Permission denied
```
That explains why the DBUS solution doesn't work for you.

`unset DISPLAY` (in both package(), check() and build()) should work for everybody.

**Comment by JonnyJD** [comment]
gna.. in my case I really need that `unset DBUS_SESSION_BUS_ADDRESS` in build(). Additionally to `unset DISPLAY`.

**Comment by JonnyJD** [comment]
Hm, since it is arguably wrong to have environment variables for sockets you don't have access to: not reported upstream.

Our workaround for allowing users to run makepkg without clearing the environment is commited to AUR in 2 parts: [7f179cbf](https://aur.archlinux.org/cgit/aur.git/commit/?h=isrcsubmit&id=7f179cbfb1050c679b37f25e92b20d0a8d515538) and [8c25731b](https://aur.archlinux.org/cgit/aur.git/commit/?h=isrcsubmit&id=8c25731b933c2809bbcefd172d2dfdd9484a7ec5) (and isrcsubmit-git accordingly).

**Comment by JonnyJD** [comment]
As noted by @Freso : while the environment is wrong, this shoudn't matter for a simple `import keyring` (reopening).

**Comment by JonnyJD** [comment]
For reference, the parts of my environment look like this:

```
DISPLAY=:0.1
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

My main user owning the dbus session has the id 1000. The user running `import keyring` has the id 1007. The socket naturally looks like this: `srw-rw-rw- 1 1000 100 0 Dec 23 01:46 /run/user/1000/bus`

**Comment by JonnyJD** [comment]
Now reported upstream in jaraco/keyring#183.

**Comment by Freso** [comment]
python-keyring 7.0-1 makes the PKGBUILD build fine without the added workarounds.

**Comment by JonnyJD** [comment]
It still breaks for me. The error message is the same, the trace is different.

**Comment by JonnyJD** [comment]
All errors fixed and now unsets necessary with python-keyring 7.0.1 and python-secretstorage 2.1.4.
