### ISSUE TITLE
Failed install on macOS 10.12

### ISSUE THREAD

**Issue by CyberSkull** [JonnyJD/musicbrainz-isrcsubmit#116]
I got a failed install when I tried via pip on macOS 10.12:

> Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-N96uKZ/isrcsubmit/setup.py", line 13, in <module>
        from isrcsubmit import __version__
      File "isrcsubmit.py", line 55, in <module>
        import discid
    ImportError: No module named discid
>    
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-N96uKZ/isrcsubmit/

**Comment by CyberSkull** [comment]
I managed to separately install discid, but it then threw this error:

>    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-HVDznY/isrcsubmit/setup.py", line 13, in <module>
        from isrcsubmit import __version__
      File "isrcsubmit.py", line 57, in <module>
        import musicbrainzngs
    ImportError: No module named musicbrainzngs
>    
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-HVDznY/isrcsubmit/

**Comment by CyberSkull** [comment]
I managed to install it after manually installing the two dependancies.

**Comment by JonnyJD** [comment]
Yes, isrcsubmit needs python-discid and musicbrainzngs.

Sorry, the setup script is not a complete standalone package installer which installs all dependencies with it, like people are used to.
Making such a thing requires a substantial amount of work (and somebody who develops on Mac)

**Comment by eli-schwartz** [comment]
Please remove the dependencies from setup.py then, as they are a lie and don't work because you don't consider using setup.py according to its intended purpose, to be a valid use case.

Somehow, nearly every other python package in existence manages to be a dependency manager with absolutely no effort whatsoever. That's why pip exists. But I guess you know better.

...

Side note: this error has nothing to do with macOS, as it is trivially reproducible on every operating system ever, merely by following the PyPA recommended method for installing every setup.py-based package ever, which works, plus yours, which doesn't.
